### ISSUE TITLE
useless set of variable is_device_path

### ISSUE THREAD

**Issue by AngeloFrangione** [likle/cwalk#19]
Hi!

I'm using cwalk in my project and i use the clang static analyzer tool for scanning my code and it scans cwalk too. 
And he finds an useless set of a variable in the code since multiple commits.
```
../../../subprojects/cwalk/src/cwalk.c:471:3: warning: Value stored to 'is_device_path' is never read
  is_device_path = false;
  ^                ~~~~~
```
That means it is useless to define it to false in the present code. Because you set it to anything else before using it.
Do you intend to use it in the future ?
It's nice that it's the only problem found by this tool, usually there are a ton !

**Comment by likle** [comment]
Hi @AngeloFrangione ! Thanks for submitting this issue. This assignment statement was there to ensure initialization, but you are right - it is not required. I removed it in https://github.com/likle/cwalk/commit/d9f7d9424ffad5ddbad5e07500aebc2ea6e84ac5 on the master branch. Please let me know if you encounter more issues!

**Comment by AngeloFrangione** [comment]
It should be fine now ! Thank you!
