### ISSUE TITLE
Invalid pointer dereference with clang-analyzer

### ISSUE THREAD

**Issue by fedegiova** [likle/cwalk#2]
Hi,

the function cwk_path_guess_style triggers a warning with clang static analyzer, I'm attaching the full report here

[report.zip](https://github.com/likle/cwalk/files/3271870/report.zip)

basically the call to cwk_path_get_last_segment at line 1386 does not initialize
segment.begin which is de-referenced the following line.

**Comment by likle** [comment]
@fedegiova Thank you for the bug report! Please let me know if you still have trouble with this issue after the previous commit.
