### ISSUE TITLE
Generate pkgconfig files

### ISSUE THREAD

**Issue by mawkish** [likle/cwalk#25]
It'd be useful if running `meson build` would generate pkg-config files.

You can do it with

```
pkg = import ('pkgconfig')
pkg.generate (cwalk)
```

I'm not sure whether you already do this in your cmake files -- I don't know cmake (and barely know meson).

I'm aware that the build instructions say use cmake, but I saw a meson.build and thought, hey, why not? And
it worked, sans pkg-config files.

**Comment by likle** [comment]
Hi @mawkish ! I will investigate on how to do that and add it.

**Comment by likle** [comment]
This has been implemented in https://github.com/likle/cwalk/commit/982e86076e570eeb64492a83fe5c0309c5c494a9
