### ISSUE TITLE
Windows path root separator is normalized

### ISSUE THREAD

**Issue by ThakeeNathees** [likle/cwalk#29]
Hi, thanks for making this library, I've been using it for my side project [pocketlang](https://github.com/ThakeeNathees/pocketlang/).

On windows `cwk_path_normalize` does not seems to change the path separator of the root from `/` to `\\` (An example provided below). Is this behavior intended or should be patched?

```ruby
>>> import path
>>> path.normpath('foo/bar/baz')
"foo\\bar\\baz"
>>> path.normpath('C:/foo/bar/baz')
"C:/foo\\bar\\baz"
```

`cwk_path_get_relative` also seems to fail because of the separator of the root

```ruby
>>> path.relpath('C:\\foo/bar/file.txt', 'C:\\foo\\bar\\baz\\')
"..\\file.txt"
>>> path.relpath('C:/foo/bar/file.txt', 'C:\\foo\\bar\\baz\\')
""
```

**Comment by likle** [comment]
Hi @ThakeeNathees ! Thanks for reporting this bug, I will have a look at it.

**Comment by likle** [comment]
Hi @ThakeeNathees ! I have made changes in the master branch. Would you like to give me some feedback whether this works better for you?

**Comment by ThakeeNathees** [comment]
@likle yup it works well and wow that was fast, thanks again. I'm closing this issue as it's resolved.
