### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ilobilo** [likle/cwalk#30]
Is cwalk thread-safe?

**Comment by likle** [comment]
Hi  @ilobilo , everything should be thread-safe except changing the path style (cwk_path_set_style/cwk_path_get_style). If you only need one path style you can set it before starting the threads and everything should be fine.

If you need to use multiple path styles in your thread you could make the following line thread local in cwalk.c (untested, requires C11):
```C
_Thread_local static enum cwk_path_style path_style = CWK_STYLE_UNIX;
````
 If you do that each thread should have their own path style and can act independently.

Does that help you?

**Comment by ilobilo** [comment]
Yes thank you
