### ISSUE TITLE
incorrect basename

### ISSUE THREAD

**Issue by freevryheid** [likle/cwalk#33]
Thanks for the library, got a question:

Perhaps I'm misunderstanding the concept of basename - the following returns a basename of 'my' with length 2 - I was expecting a null string with length 0.

``` c
#include <cwalk.h>
#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
  const·char·*basename;
  size_t length;
  cwk_path_set_style(CWK_STYLE_UNIX);  
  cwk_path_get_basename("/my/", &basename, &length);
  printf("The basename is: '%.*s'", length, basename);
  return EXIT_SUCCESS;
}
```

**Comment by likle** [comment]
Hi @freevryheid 

Thanks for asking. The [basename](https://en.wikipedia.org/wiki/Basename) is the [last segment of the path](https://likle.github.io/cwalk/reference/cwk_path_get_basename.html). Maybe you are looking for [cwk_path_get_dirname](https://likle.github.io/cwalk/reference/cwk_path_get_dirname.html) instead?

**Comment by freevryheid** [comment]
Got it - thanks!
