### ISSUE TITLE
When using local copy of project (clib installed) compiler looks for system installed header

### ISSUE THREAD

**Issue by phoenixpinpoint** [likle/cwalk#41]
When I install with Clib the compiler is looking for cwalk.h in other locations not my local copy.

**Comment by phoenixpinpoint** [comment]
Example: 
/deps/cwalk contains
cwalk.c
cwalkh.

Since cwalk.c references #include<cwalk.h> without a bearing to location we cannot simply change to #include "include/cwalk.h"
Rather what would need to be done is either updating cwalk.c to point to include "cwalk.h" or somehow get clib to support creating the directory which I am unsure if it can do.

**Comment by likle** [comment]
Hi @phoenixpinpoint , thanks for reporting this issue. We can't simply change that because it would break other people's builds.
The library currently requires you to add the directory which contains the header file to the include directories (see [directly embed cwalk in your source](https://likle.github.io/cwalk/embed.html#directly-embed-cwalk-in-your-source))

**Comment by phoenixpinpoint** [comment]
Of course. I am wondering if there is a solution within the clibs configuration....to allow for the code base to stay the same but for clibs to be inline with others clibs projects (ie. source and header files being in and referencing the /deps directory). 

I can try to sort that out and see. Although this would mean that people using clibs to install on the next install it could break their build. I am not sure you would be willing to allow this. My intent would be to have clibs install it like any other clibs package (clibs/buffer for example). 

I for one am using a simple makefile for what I am doing. I could modify my makefile to add the deps directory as and include this would solve it for me. This may actually be better as if I just unilaterally included the deps directory I wouldn't have to use #include "<some relative path>/deps" on my header includes.......Really this is the right way to do it.....so yeah.........

Apologies it has been a while since I have actually built C code of any magnitude.....seems I have been in the JavaScript world for too long.......

Thanks for your help @likle  and really do love what you have done here.

**Comment by likle** [comment]
Thanks @phoenixpinpoint ! Let me know if you need help 🙂
