### ISSUE TITLE
Consider producing a new release

### ISSUE THREAD

**Issue by antoniovazquezblanco** [likle/cwalk#42]
I am currently working on contributing a wrap file to wrapdb to be able to use cwalk as a meson dependency with a single command.

Latest release contains a meson.build file that produces warnings and that should be avoided. It seems though as those warnings have already been patched.

It would be awesome if a new release could be cut, containing those fixes.

Thanks!

**Comment by likle** [comment]
Hi @antoniovazquezblanco , there is not much in it, but I release [v1.2.8](https://github.com/likle/cwalk/releases/tag/v1.2.8).
